### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by jiahuif**
seriously use spell checker lol

### CODE REVIEW

**Comment by jiahuif** [comment]
CI error lol

**Comment by shuding** [comment]
@IndeedPlusPlus Travis CI do not have the permission to access (SSH) your repo (PR)

**Comment by jiahuif** [comment]
Maybe you should set CI to clone via https

**Comment by dnc1994** [comment]
@IndeedPlusPlus We have already decided to invite you to HumanLearn. Will you support it or not?

**Comment by jiahuif** [comment]
I zici. Actually I am going to start the course on Coursera right now.

**Pull request merged**
